

development:
  adapter: postgresql
  encoding: unicode
  database: empower_development
  pool: 5
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: empower_test
  pool: 5
  username: postgres
  password: password